### ISSUE TITLE
Even extremely long "tap"s are registered as middle clicks

### ISSUE THREAD

**Issue by alicangok** [artginzburg/MiddleClick-Sonoma#39]
Is this expected behavior?

I was under the impression that there if a "tap" (the time between putting fingers on the touchpad and lifting them) lasted more than a specified time, maybe on the order of a few hundred milliseconds, it would no longer be registered as a tap. But this application considers putting 3 fingers on the touchpad for multiple seconds (10 seconds even) as taps, hence the middleclick behavior is triggered.

(I'm on an M1 Air by the way, not sure if other models exhibit this behavior)

Thanks

**Comment by 66Ton99** [comment]
Yes, it is the sam on MacBook Pro 16 2019. It triggers middle click if you do force click too.

**Comment by artginzburg** [comment]
It is kinda easy to fix, the only thing I'm not sure about is how long a tap should be to not be considered a hold.

> Also just reminding myself here that this behavior should not apply in click-only mode.

**Comment by artginzburg** [comment]
Fixed in #62
