### ISSUE TITLE
Can't open MiddleClick on version 12.6 (21G115)

### ISSUE THREAD

**Issue by jasonm-ps** [artginzburg/MiddleClick-Sonoma#50]
“MiddleClick” can’t be opened because Apple cannot check it for malicious software.

**Comment by artginzburg** [comment]
That's ok for open source apps. Just open it using Ctrl+Click > `Open`

**Comment by s0menickname** [comment]
That doesn't work though...

**Comment by artginzburg** [comment]
This is strange. Is your System Preferences > `Security & Privacy` > `General` > `Allow apps downloaded from:` set to "App Store and identified developers"?

**Comment by s0menickname** [comment]
Yes. A downgrade to older version helped, by the way

**Comment by artginzburg** [comment]
Is this related to Homebrew installation or manual download? Also, which version works?

**Comment by artk42** [comment]
> Is this related to Homebrew installation or manual download? Also, which version works?

Just faced the same problem again after upgrading to 2.6.1 from 2.5.0.1 using brew

**Comment by artginzburg** [comment]
Have you found a way to open the app though?

**Comment by artk42** [comment]
Yes, there option to Open appears if try to Open using right-click menu

**Comment by artginzburg** [comment]
Then it works as expected. The app is not signed by a paid certificate, and Apple obviously doesn't check it for malicious software for free.
