### ISSUE TITLE
Should a new release be cut?

### ISSUE THREAD

**Issue by darianss** [artginzburg/MiddleClick-Sonoma#85]
Tried building and singing this locally, and it works much better with the changes since Jan.

**Comment by artginzburg** [comment]
Yes, thanks for the feedback. Just need to decide on this first: https://github.com/artginzburg/MiddleClick-Sonoma/pull/62#issuecomment-1772202538

**Comment by samdenty** [comment]
is there any update to this @artginzburg?

**Comment by samdenty** [comment]
if not, it would be nice if you could add build instructions so we can get this working @artginzburg

**Comment by artginzburg** [comment]
Here is the release: https://github.com/artginzburg/MiddleClick-Sonoma/releases/tag/2.7
